<?php
/**
 * Helper.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\HelperModule\Form\Type;

use MU\HelperModule\Form\Type\Base\AbstractProductClassType;

/**
 * Product class editing form type implementation class.
 */
class ProductClassType extends AbstractProductClassType
{
    // feel free to extend the product class editing form type class here
}
