<?php
/**
 * Helper.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\HelperModule\DependencyInjection;

use MU\HelperModule\DependencyInjection\Base\AbstractMUHelperExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class MUHelperExtension extends AbstractMUHelperExtension
{
    // custom enhancements can go here
}
