<?php
/**
 * Helper.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\HelperModule\Event;

use MU\HelperModule\Event\Base\AbstractFilterProductClassEvent;

/**
 * Event implementation class for filtering product class processing.
 */
class FilterProductClassEvent extends AbstractFilterProductClassEvent
{
    // feel free to extend the event class here
}
