<?php
/**
 * Helper.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\HelperModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\HelperModule\Entity\ProductClassEntity;

/**
 * Event base class for filtering product class processing.
 */
class AbstractFilterProductClassEvent extends Event
{
    /**
     * @var ProductClassEntity Reference to treated entity instance.
     */
    protected $productClass;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterProductClassEvent constructor.
     *
     * @param ProductClassEntity $productClass Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(ProductClassEntity $productClass, $entityChangeSet = [])
    {
        $this->productClass = $productClass;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return ProductClassEntity
     */
    public function getProductClass()
    {
        return $this->productClass;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
