<?php
/**
 * Helper.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\HelperModule\Form\Type\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;

/**
 * Configuration form type base class.
 */
abstract class AbstractConfigType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var array
     */
    protected $moduleVars;

    /**
     * ConfigType constructor.
     *
     * @param TranslatorInterface $translator  Translator service instance
     * @param object              $moduleVars  Existing module vars
     */
    public function __construct(
        TranslatorInterface $translator,
        $moduleVars
    ) {
        $this->setTranslator($translator);
        $this->moduleVars = $moduleVars;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addAmazonSettingsFields($builder, $options);
        $this->addDisplaySettingsFields($builder, $options);
        $this->addListViewsFields($builder, $options);

        $builder
            ->add('save', SubmitType::class, [
                'label' => $this->__('Update configuration'),
                'icon' => 'fa-check',
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
            ->add('cancel', SubmitType::class, [
                'label' => $this->__('Cancel'),
                'icon' => 'fa-times',
                'attr' => [
                    'class' => 'btn btn-default',
                    'formnovalidate' => 'formnovalidate'
                ]
            ])
        ;
    }

    /**
     * Adds fields for amazon settings fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addAmazonSettingsFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('accessKey', TextType::class, [
                'label' => $this->__('Access key') . ':',
                'required' => false,
                'data' => isset($this->moduleVars['accessKey']) ? $this->moduleVars['accessKey'] : '',
                'empty_data' => '',
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the access key.')
                ],
            ])
            ->add('secretKey', TextType::class, [
                'label' => $this->__('Secret key') . ':',
                'required' => false,
                'data' => isset($this->moduleVars['secretKey']) ? $this->moduleVars['secretKey'] : '',
                'empty_data' => '',
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the secret key.')
                ],
            ])
            ->add('associateKey', TextType::class, [
                'label' => $this->__('Associate key') . ':',
                'required' => false,
                'data' => isset($this->moduleVars['associateKey']) ? $this->moduleVars['associateKey'] : '',
                'empty_data' => '',
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the associate key.')
                ],
            ])
            ->add('passwordForImport', TextType::class, [
                'label' => $this->__('Password for import') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Password for import.')
                ],
                'help' => $this->__('Password for import.'),
                'required' => false,
                'data' => isset($this->moduleVars['passwordForImport']) ? $this->moduleVars['passwordForImport'] : '',
                'empty_data' => '',
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the password for import.')
                ],
            ])
            ->add('amountForImport', IntegerType::class, [
                'label' => $this->__('Amount for import') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Number of imports per cronjob')
                ],
                'help' => $this->__('Number of imports per cronjob'),
                'required' => false,
                'data' => isset($this->moduleVars['amountForImport']) ? intval($this->moduleVars['amountForImport']) : intval(4),
                'empty_data' => intval('4'),
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the amount for import.') . ' ' . $this->__('Only digits are allowed.')
                ],'scale' => 0
            ])
        ;
    }

    /**
     * Adds fields for display settings fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addDisplaySettingsFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('textForDetailLink', TextType::class, [
                'label' => $this->__('Text for detail link') . ':',
                'required' => false,
                'data' => isset($this->moduleVars['textForDetailLink']) ? $this->moduleVars['textForDetailLink'] : '',
                'empty_data' => 'Bei Amazon erh?ltlich',
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the text for detail link.')
                ],
            ])
            ->add('textForAddToWishlist', TextType::class, [
                'label' => $this->__('Text for add to wishlist') . ':',
                'required' => false,
                'data' => isset($this->moduleVars['textForAddToWishlist']) ? $this->moduleVars['textForAddToWishlist'] : '',
                'empty_data' => '',
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the text for add to wishlist.')
                ],
            ])
            ->add('showPerCent', CheckboxType::class, [
                'label' => $this->__('Show per cent') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('If enabled percentage saved is shown otherwise amount saved.')
                ],
                'help' => $this->__('If enabled percentage saved is shown otherwise amount saved.'),
                'required' => false,
                'data' => (bool)(isset($this->moduleVars['showPerCent']) ? $this->moduleVars['showPerCent'] : false),
                'attr' => [
                    'title' => $this->__('The show per cent option.')
                ],
            ])
        ;
    }

    /**
     * Adds fields for list views fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addListViewsFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('productClassEntriesPerPage', IntegerType::class, [
                'label' => $this->__('Product class entries per page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The amount of product classes shown per page')
                ],
                'help' => $this->__('The amount of product classes shown per page'),
                'required' => false,
                'data' => isset($this->moduleVars['productClassEntriesPerPage']) ? intval($this->moduleVars['productClassEntriesPerPage']) : intval(10),
                'empty_data' => intval('10'),
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the product class entries per page.') . ' ' . $this->__('Only digits are allowed.')
                ],'scale' => 0
            ])
        ;
    }

    /**
     * @inheritDoc
     */
    public function getBlockPrefix()
    {
        return 'muhelpermodule_config';
    }
}
