<?php
/**
 * Helper.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\HelperModule\Form\Type\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use MU\HelperModule\Entity\Factory\EntityFactory;
use MU\HelperModule\Form\Type\Field\ArrayType;
use MU\HelperModule\Helper\ListEntriesHelper;

/**
 * Product class editing form type base class.
 */
abstract class AbstractProductClassType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var EntityFactory
     */
    protected $entityFactory;

    /**
     * @var ListEntriesHelper
     */
    protected $listHelper;

    /**
     * ProductClassType constructor.
     *
     * @param TranslatorInterface $translator    Translator service instance
     * @param EntityFactory $entityFactory EntityFactory service instance
     * @param ListEntriesHelper $listHelper ListEntriesHelper service instance
     */
    public function __construct(
        TranslatorInterface $translator,
        EntityFactory $entityFactory,
        ListEntriesHelper $listHelper
    ) {
        $this->setTranslator($translator);
        $this->entityFactory = $entityFactory;
        $this->listHelper = $listHelper;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addEntityFields($builder, $options);
        $this->addReturnControlField($builder, $options);
        $this->addSubmitButtons($builder, $options);
    }

    /**
     * Adds basic entity fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addEntityFields(FormBuilderInterface $builder, array $options)
    {
        
        $builder->add('title', TextType::class, [
            'label' => $this->__('Title') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the title of the product class')
            ],
            'required' => true,
        ]);
        
        $builder->add('description', TextareaType::class, [
            'label' => $this->__('Description') . ':',
            'help' => $this->__f('Note: this value must not exceed %amount% characters.', ['%amount%' => 5000]),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 5000,
                'class' => '',
                'title' => $this->__('Enter the description of the product class')
            ],
            'required' => false,
        ]);
        
        $builder->add('productDetails', ArrayType::class, [
            'label' => $this->__('Product details') . ':',
            'help' => $this->__('Enter one entry per line.'),
            'empty_data' => '',
            'attr' => [
                'class' => '',
                'title' => $this->__('Enter the product details of the product class')
            ],
            'required' => false,
        ]);
        
        $builder->add('getAmazonDatas', CheckboxType::class, [
            'label' => $this->__('Get amazon datas') . ':',
            'attr' => [
                'class' => '',
                'title' => $this->__('get amazon datas ?')
            ],
            'required' => false,
        ]);
        
        $builder->add('operation', TextType::class, [
            'label' => $this->__('Operation') . ':',
            'empty_data' => 'ItemSearch',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the operation of the product class')
            ],
            'required' => true,
        ]);
        
        $builder->add('responseGroup', TextType::class, [
            'label' => $this->__('Response group') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('It is possible to enter them comma seperated.
                Possible Values: Small, Medium, Large,
                BrowseNodes,Offers,OfferSummary,VariationSummary
                ')
            ],
            'help' => $this->__('It is possible to enter them comma seperated.
            Possible Values: Small, Medium, Large,
            BrowseNodes,Offers,OfferSummary,VariationSummary
            '),
            'empty_data' => 'BrowseNodes,Large,Offers,OfferSummary,VariationSummary',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the response group of the product class')
            ],
            'required' => true,
        ]);
        
        $builder->add('searchIndex', TextType::class, [
            'label' => $this->__('Search index') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('Possible values:
                All, Apparel, Books,Electronics,SportingGoods
                ')
            ],
            'help' => $this->__('Possible values:
            All, Apparel, Books,Electronics,SportingGoods
            '),
            'empty_data' => 'All',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the search index of the product class')
            ],
            'required' => true,
        ]);
        
        $builder->add('keywordsForImport', TextType::class, [
            'label' => $this->__('Keywords for import') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('Also a phrase, keywords without komma.')
            ],
            'help' => $this->__('Also a phrase, keywords without komma.'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the keywords for import of the product class')
            ],
            'required' => false,
        ]);
        
        $builder->add('sortOfImport', TextType::class, [
            'label' => $this->__('Sort of import') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('Valid values are:
                salesrank,reviewrank,pricerank,inverse-pricerank,
                -pubdate,titlerank,-titlerank,price,-price,
                -publication_date,-unit-sales,relevancerank')
            ],
            'help' => $this->__('Valid values are:
            salesrank,reviewrank,pricerank,inverse-pricerank,
            -pubdate,titlerank,-titlerank,price,-price,
            -publication_date,-unit-sales,relevancerank'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 100,
                'class' => '',
                'title' => $this->__('Enter the sort of import of the product class')
            ],
            'required' => false,
        ]);
        
        $builder->add('additionalFilter', TextType::class, [
            'label' => $this->__('Additional filter') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('comma and semicolon seperated
                ')
            ],
            'help' => $this->__('comma and semicolon seperated
            '),
            'empty_data' => 'Availability,Available;BrowseNode,3024033031',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the additional filter of the product class')
            ],
            'required' => false,
        ]);
        
        $builder->add('includeReviewSummary', CheckboxType::class, [
            'label' => $this->__('Include review summary') . ':',
            'attr' => [
                'class' => '',
                'title' => $this->__('include review summary ?')
            ],
            'required' => false,
        ]);
        
        $builder->add('itemPageForImport', IntegerType::class, [
            'label' => $this->__('Item page for import') . ':',
            'empty_data' => '5',
            'attr' => [
                'maxlength' => 11,
                'class' => ' validate-digits',
                'title' => $this->__('Enter the item page for import of the product class.') . ' ' . $this->__('Only digits are allowed.')
            ],
            'required' => false,
            'scale' => 0
        ]);
        
        $builder->add('associateKeyOfAmazon', TextType::class, [
            'label' => $this->__('Associate key of amazon') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 100,
                'class' => '',
                'title' => $this->__('Enter the associate key of amazon of the product class')
            ],
            'required' => false,
        ]);
        
        $builder->add('amazonDate', DateType::class, [
            'label' => $this->__('Amazon date') . ':',
            'empty_data' => '',
            'attr' => [
                'class' => '',
                'title' => $this->__('Enter the amazon date of the product class')
            ],
            'required' => false,
            'empty_data' => null,
            'widget' => 'single_text'
        ]);
        
        $builder->add('amazonTime', TimeType::class, [
            'label' => $this->__('Amazon time') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 8,
                'class' => '',
                'title' => $this->__('Enter the amazon time of the product class')
            ],
            'required' => false,
            'empty_data' => '',
            'widget' => 'single_text'
        ]);
        
        $builder->add('amountOfImport', IntegerType::class, [
            'label' => $this->__('Amount of import') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 11,
                'class' => ' validate-digits',
                'title' => $this->__('Enter the amount of import of the product class.') . ' ' . $this->__('Only digits are allowed.')
            ],
            'required' => false,
            'scale' => 0
        ]);
    }

    /**
     * Adds the return control field.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addReturnControlField(FormBuilderInterface $builder, array $options)
    {
        if ($options['mode'] != 'create') {
            return;
        }
        $builder->add('repeatCreation', CheckboxType::class, [
            'mapped' => false,
            'label' => $this->__('Create another item after save'),
            'required' => false
        ]);
    }

    /**
     * Adds submit buttons.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addSubmitButtons(FormBuilderInterface $builder, array $options)
    {
        foreach ($options['actions'] as $action) {
            $builder->add($action['id'], SubmitType::class, [
                'label' => $action['title'],
                'icon' => ($action['id'] == 'delete' ? 'fa-trash-o' : ''),
                'attr' => [
                    'class' => $action['buttonClass']
                ]
            ]);
        }
        $builder->add('reset', ResetType::class, [
            'label' => $this->__('Reset'),
            'icon' => 'fa-refresh',
            'attr' => [
                'class' => 'btn btn-default',
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
        $builder->add('cancel', SubmitType::class, [
            'label' => $this->__('Cancel'),
            'icon' => 'fa-times',
            'attr' => [
                'class' => 'btn btn-default',
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
    }

    /**
     * @inheritDoc
     */
    public function getBlockPrefix()
    {
        return 'muhelpermodule_productclass';
    }

    /**
     * @inheritDoc
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                // define class for underlying data (required for embedding forms)
                'data_class' => 'MU\HelperModule\Entity\ProductClassEntity',
                'empty_data' => function (FormInterface $form) {
                    return $this->entityFactory->createProductClass();
                },
                'error_mapping' => [
                ],
                'mode' => 'create',
                'actions' => [],
            ])
            ->setRequired(['mode', 'actions'])
            ->setAllowedTypes('mode', 'string')
            ->setAllowedTypes('actions', 'array')
            ->setAllowedValues('mode', ['create', 'edit'])
        ;
    }
}
