<?php
/**
 * Helper.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\HelperModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractHelperEvents
{
    /**
     * The muhelpermodule.productclass_post_load event is thrown when product classes
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\HelperModule\Event\FilterProductClassEvent instance.
     *
     * @see MU\HelperModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const PRODUCTCLASS_POST_LOAD = 'muhelpermodule.productclass_post_load';
    
    /**
     * The muhelpermodule.productclass_pre_persist event is thrown before a new product class
     * is created in the system.
     *
     * The event listener receives an
     * MU\HelperModule\Event\FilterProductClassEvent instance.
     *
     * @see MU\HelperModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const PRODUCTCLASS_PRE_PERSIST = 'muhelpermodule.productclass_pre_persist';
    
    /**
     * The muhelpermodule.productclass_post_persist event is thrown after a new product class
     * has been created in the system.
     *
     * The event listener receives an
     * MU\HelperModule\Event\FilterProductClassEvent instance.
     *
     * @see MU\HelperModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const PRODUCTCLASS_POST_PERSIST = 'muhelpermodule.productclass_post_persist';
    
    /**
     * The muhelpermodule.productclass_pre_remove event is thrown before an existing product class
     * is removed from the system.
     *
     * The event listener receives an
     * MU\HelperModule\Event\FilterProductClassEvent instance.
     *
     * @see MU\HelperModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const PRODUCTCLASS_PRE_REMOVE = 'muhelpermodule.productclass_pre_remove';
    
    /**
     * The muhelpermodule.productclass_post_remove event is thrown after an existing product class
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\HelperModule\Event\FilterProductClassEvent instance.
     *
     * @see MU\HelperModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const PRODUCTCLASS_POST_REMOVE = 'muhelpermodule.productclass_post_remove';
    
    /**
     * The muhelpermodule.productclass_pre_update event is thrown before an existing product class
     * is updated in the system.
     *
     * The event listener receives an
     * MU\HelperModule\Event\FilterProductClassEvent instance.
     *
     * @see MU\HelperModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const PRODUCTCLASS_PRE_UPDATE = 'muhelpermodule.productclass_pre_update';
    
    /**
     * The muhelpermodule.productclass_post_update event is thrown after an existing new product class
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\HelperModule\Event\FilterProductClassEvent instance.
     *
     * @see MU\HelperModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const PRODUCTCLASS_POST_UPDATE = 'muhelpermodule.productclass_post_update';
    
}
