<?php
/**
 * Helper.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\HelperModule\HookSubscriber;

use MU\HelperModule\HookSubscriber\Base\AbstractProductClassFilterHooksSubscriber;

/**
 * Implementation class for filter hooks subscriber.
 */
class ProductClassFilterHooksSubscriber extends AbstractProductClassFilterHooksSubscriber
{
    // feel free to add your own convenience methods here
}
